CC ?= gcc
CFLAGS = -Wall -g
os_cpp = `if [ -x ../myconfig_guess ]; then ../myconfig_guess --cflags; fi`
CFLAGS += $(os_cpp)
CFLAGS += -I../src

all: growlnotify

libgrowl.o: ../src/libgrowl.c
	$(CC) $(CFLAGS) -c ../src/libgrowl.c -I../src

growlnotify: growlnotify.o libgrowl.o
	$(CC) -o growlnotify growlnotify.o libgrowl.o

clean:
	rm -f growlnotify
	rm -f *.o
